from __future__ import annotations

import json
import uuid

from pathlib import Path


from config import (
    IS_VALIDATION_MODE,
)

from endpoint.storage.database import (
    initialize_database,
)

from endpoint.collectors.fusion_v3_primary_process_monitor import (
    FusionV3PrimaryProcessMonitor,
)

from detection.fusion.incident_store import (
    IncidentStore,
)

import validation.process.powershell_batch_runner as powershell_validation


# ================================================================
# CONFIG
# ================================================================

RUN_ID = (
    "SOC-VERTICAL-SLICE-"
    + uuid.uuid4().hex[:8].upper()
)


REPORT_DIR = (
    Path(__file__)
    .resolve()
    .parents[1]
    / "reports"
)


REPORT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


REPORT_PATH = (
    REPORT_DIR
    / "soc_vertical_slice_seed.json"
)


# ================================================================
# MAIN
# ================================================================

def main():

    if not IS_VALIDATION_MODE:

        raise RuntimeError(
            "SOC vertical slice must run "
            "in VALIDATION mode."
        )


    print(
        "=" * 78
    )

    print(
        "SENTINEL-X SOC VERTICAL SLICE SEED"
    )

    print(
        "Run:",
        RUN_ID
    )

    print(
        "=" * 78
    )


    # ============================================================
    # DATABASE
    # ============================================================

    initialize_database()


    # ============================================================
    # USE THIS RUN ID FOR THE EXISTING POWERSHELL VALIDATOR
    # ============================================================

    powershell_validation.VALIDATION_RUN_ID = (
        RUN_ID
    )


    # ============================================================
    # LOAD REAL PROCESS PIPELINE
    # ============================================================

    monitor = (
        FusionV3PrimaryProcessMonitor(
            poll_interval=2.0
        )
    )


    # ============================================================
    # RUN THE PROVEN 8-STEP TEMPORAL SCENARIO
    # ============================================================

    result = (
        powershell_validation
        .run_temporal_scenario(
            monitor
        )
    )


    # ============================================================
    # COLLECT THE EVENT IDS GENERATED BY THIS SCENARIO
    # ============================================================

    event_ids = set()


    for step in (
        result.get(
            "sequence_steps",
            []
        )
        or []
    ):

        event_id = (
            step.get(
                "event_id"
            )
        )


        if event_id:

            event_ids.add(
                str(
                    event_id
                )
            )


    # ============================================================
    # FIND INCIDENT CREATED FROM THESE EVENTS
    # ============================================================

    incident_store = (
        IncidentStore()
    )


    incidents = (
        incident_store.get_incidents()
        or []
    )


    matching_incidents = []


    for incident in incidents:

        incident_event_ids = {

            str(
                value
            )

            for value
            in (
                incident.get(
                    "event_ids",
                    []
                )
                or []
            )
        }


        if (
            incident_event_ids
            & event_ids
        ):

            matching_incidents.append(
                incident
            )


    # ============================================================
    # RESULT
    # ============================================================

    if not matching_incidents:

        print()

        print(
            "FAILED:"
        )

        print(
            "The detection sequence ran, "
            "but no correlated incident "
            "was found."
        )

        raise RuntimeError(
            "Vertical-slice incident "
            "was not created."
        )


    # Prefer incident containing most seed events.
    matching_incidents.sort(

        key=lambda incident:
            len(
                set(
                    str(value)

                    for value
                    in (
                        incident.get(
                            "event_ids",
                            []
                        )
                        or []
                    )
                )
                & event_ids
            ),

        reverse=True,
    )


    selected = (
        matching_incidents[
            0
        ]
    )


    incident_id = (
        selected.get(
            "incident_id"
        )
    )


    payload = {

        "run_id":
            RUN_ID,

        "success":
            True,

        "incident_id":
            incident_id,

        "seed_event_ids":
            sorted(
                event_ids
            ),

        "incident":
            selected,

        "detector_result": {

            "rule_score":
                (
                    result.get(
                        "rule",
                        {}
                    )
                    or {}
                ).get(
                    "behavior_score"
                ),

            "temporal":
                result.get(
                    "temporal"
                ),

            "fusion_score":
                (
                    result.get(
                        "fusion",
                        {}
                    )
                    or {}
                ).get(
                    "fusion_score"
                ),

            "severity":
                (
                    result.get(
                        "fusion",
                        {}
                    )
                    or {}
                ).get(
                    "severity"
                ),

            "should_alert":
                (
                    result.get(
                        "fusion",
                        {}
                    )
                    or {}
                ).get(
                    "should_alert"
                ),

            "stored_detection_count":
                result.get(
                    "stored_detection_count"
                ),
        },
    }


    with open(
        REPORT_PATH,
        "w",
        encoding="utf-8",
    ) as handle:

        json.dump(
            payload,
            handle,
            indent=2,
            default=str,
        )


    print()

    print(
        "VERTICAL SLICE SEED CREATED"
    )

    print(
        "-" * 78
    )

    print(
        "Incident ID:",
        incident_id
    )

    print(
        "Seed events:",
        len(
            event_ids
        )
    )

    print(
        "Fusion score:",
        payload[
            "detector_result"
        ][
            "fusion_score"
        ]
    )

    print(
        "Severity:",
        payload[
            "detector_result"
        ][
            "severity"
        ]
    )

    print(
        "Report:",
        REPORT_PATH
    )

    print(
        "=" * 78
    )


if __name__ == "__main__":

    main()